package com.expense.expensereimbursement.entity;

import javax.persistence.Column;

import javax.persistence.Entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import javax.persistence.Table;

@Entity
@Table(name = "users")
public class UserEntity {
	@Id // informs the framework that this is the primary key column
	@GeneratedValue(strategy = GenerationType.IDENTITY) // informs the framework that it is an autogenerated identity
														// column
	@Column(name = "user_id") // maps the property id to the column book_id of the DB
	private int userId;

	@Column(name = "user_firstname")
	private String userFirstName;

	@Column(name = "user_lastname")
	private String userLastName;

	@Column(name = "user_email")
	private String userEmail;

	@Column(name = "user_password")
	private String userPassword;

	@Column(name = "user_role")
	private String userRole;

//	@OneToMany(mappedBy = "userEntity", fetch = FetchType.LAZY)
//	private Set requests;

	public UserEntity() {

	}

	public UserEntity(String userFirstName, String userLastName, String userEmail, String userPassword,
			String userRole) {
		super();
		this.userFirstName = userFirstName;
		this.userLastName = userLastName;
		this.userEmail = userEmail;
		this.userPassword = userPassword;
		this.userRole = userRole;
	}

	public UserEntity(int userId, String userFirstName, String userLastName, String userEmail, String userPassword,
			String userRole) {
		super();
		this.userId = userId;
		this.userFirstName = userFirstName;
		this.userLastName = userLastName;
		this.userEmail = userEmail;
		this.userPassword = userPassword;
		this.userRole = userRole;
	}

	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getUserFirstName() {
		return userFirstName;
	}

	public void setUserFirstName(String userFirstName) {
		this.userFirstName = userFirstName;
	}

	public String getUserLastName() {
		return userLastName;
	}

	public void setUserLastName(String userLastName) {
		this.userLastName = userLastName;
	}

	public String getUserEmail() {
		return userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public String getUserPassword() {
		return userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getUserRole() {
		return userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	@Override
	public String toString() {
		return "UserEntity [userId=" + userId + ", userFirstName=" + userFirstName + ", userLastName=" + userLastName
				+ ", userEmail=" + userEmail + ", userPassword=" + userPassword + ", userRole=" + userRole + "]";
	}

}
