package com.expense.expensereimbursement.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="requests")
public class RequestEntity {
	@Id // informs the framework that this is the primary key column
	@GeneratedValue(strategy = GenerationType.IDENTITY) // informs the framework that it is an autogenerated identity column
	@Column(name="request_id") // maps the property id to the column book_id of the DB
	private int requestId;
	
	@Column(name="request_userid")
	private int userId;
	
	@Column(name="request_amount")
	private double requestAmount;
	
	@Column(name="request_description")
	private String requestDescription;
	
	@Column(name="request_status")
	private String RequestStatus;
	
	@Column(name="request_imageURL")
	private String requestImageURL;
	
	@Column(name="request_requesttime")
	private String requestTime;
	
	@Column(name="request_resolvedtime")
	private String resolvedTime;

	// association mappings - for foreign key columns
	
	// framework expects you to provide a default constructor
	public RequestEntity() {
	
	}

	
	public RequestEntity(int userId, double requestAmount, String requestDescription, String requestStatus,
			String requestImageURL, String requestTime, String resolvedTime) {
		super();
		this.userId = userId;
		this.requestAmount = requestAmount;
		this.requestDescription = requestDescription;
		RequestStatus = requestStatus;
		this.requestImageURL = requestImageURL;
		this.requestTime = requestTime;
		this.resolvedTime = resolvedTime;
	}


	

	public RequestEntity(int requestId, int userId, double requestAmount, String requestDescription,
			String requestStatus, String requestImageURL, String requestTime, String resolvedTime) {
		super();
		this.requestId = requestId;
		this.userId = userId;
		this.requestAmount = requestAmount;
		this.requestDescription = requestDescription;
		RequestStatus = requestStatus;
		this.requestImageURL = requestImageURL;
		this.requestTime = requestTime;
		this.resolvedTime = resolvedTime;
	}


	public int getRequestId() {
		return requestId;
	}


	public void setRequestId(int requestId) {
		this.requestId = requestId;
	}


	public int getUserId() {
		return userId;
	}


	public void setUserId(int userId) {
		this.userId = userId;
	}


	public double getRequestAmount() {
		return requestAmount;
	}


	public void setRequestAmount(double requestAmount) {
		this.requestAmount = requestAmount;
	}


	public String getRequestDescription() {
		return requestDescription;
	}


	public void setRequestDescription(String requestDescription) {
		this.requestDescription = requestDescription;
	}


	public String getRequestStatus() {
		return RequestStatus;
	}


	public void setRequestStatus(String requestStatus) {
		RequestStatus = requestStatus;
	}


	public String getRequestImageURL() {
		return requestImageURL;
	}


	public void setRequestImageURL(String requestImageURL) {
		this.requestImageURL = requestImageURL;
	}


	public String getRequestTime() {
		return requestTime;
	}


	public void setRequestTime(String requestTime) {
		this.requestTime = requestTime;
	}


	public String getResolvedTime() {
		return resolvedTime;
	}


	public void setResolvedTime(String resolvedTime) {
		this.resolvedTime = resolvedTime;
	}


	@Override
	public String toString() {
		return "RequestEntity [requestId=" + requestId + ", userId=" + userId + ", requestAmount=" + requestAmount
				+ ", requestDescription=" + requestDescription + ", RequestStatus=" + RequestStatus
				+ ", requestImageURL=" + requestImageURL + ", requestTime=" + requestTime + ", resolvedTime="
				+ resolvedTime + "]";
	}


	
}
